### PR TITLE
Added start and end graphics for a polyline

### PR DESCRIPTION
**Pull request by kgonzago**
@nickcam Your code was structured and doc'ed well. I added a mini enhancement for a start and end graphic, and provided the option of hiding arrows along a polyline. Please review at your convenience.

### CODE REVIEW

**Comment by nickcam** [comment]
Hi @kgonzago,

Thanks for this! Had a quick look and it looks good, bit of a tidy up in there as well which is always welcome :).
Just a couple of points.
- I think the showArrowsAlongLine prop should default to true. Probably rename it to showDirectionalSymbols just to be consistent with the other properties related to those symbols.
- Would add a boolean property for adding the start and end symbols as well, probably default it to false...so callers can choose to add them or not.

I can accept the PR and make the updates above after merging it or I can make them in your forked copy and you can create another PR after reviewing them...what would you prefer?

Thanks,
Nick

**Comment by kgonzago** [comment]
@nickcam Agreed on both points. I'll make the necessary changes and create another PR.

**Comment by kgonzago** [comment]
@nickcam Please review PR at your convenience.

**Comment by nickcam** [comment]
Thanks mate - nice work!

**Pull request merged**
