### PR TITLE
Added ability to animate lines

### PR DESCRIPTION
**Pull request by cmosnick**
Hey Nick, this widget is great!  Here are a few additions I made:  
- Added ability to add CSS animations for SVG <path>
- Animations will need to be specified in CSS external to the widget, as shown in example.
- Direction Graphic functionality remains the same, except the default is now no graphic unless directionSymbol is specified.

Let me know what you think, and if you have any suggestions moving forward.

### CODE REVIEW

**Comment by nickcam** [comment]
Hi @cmosnick,
This is good stuff - the animated line looks great!
I've got a couple of tweaks to make to it - IE/Edge fix and couple of other little things.

Coming from a SS/svn/TFS background my knowledge of git is currently limited to the basics of github usage. What I was worried I would do is make the changes, commit them (including your changes) but then your commits would be wiped / not credited.

I was following the instructions here - [https://help.github.com/articles/checking-out-pull-requests-locally/](https://help.github.com/articles/checking-out-pull-requests-locally/) - to create a local branch of your commits to edit and then merge back into master. Do you know if that will wipe your commits from the history though - couldn't find any info on whether that workflow will wipe them out?

Thanks,
Nick

**Comment by nickcam** [comment]
Hi @cmosnick,

I've just had a chance to create a branch to try and merge the PR, and I realized that I wouldn't add the changes as they are without making wholesale changes sorry. Here's why:
- Change folder name. Agree the folder name should be changed, but not to 'widget', only because the class isn't technically a widget, as in it doesn't inherit from dojo's widget or baseWidget, so widget might be slightly confusing. Suggest just 'dsl' or something else.
- Default directionSymbol to null. Would prefer to keep it to default to a value, eg 'arrow1' as without the symbol there's no point in using this class - should just use a standard SimpleLineSymbol. If someone wanted to animate that line they could just apply a class to the graphic node and have it animate via css.
- Don't add property/option animateLine - Again slightly confusing as it doesn't actually animate, just adds a class for animation to happen externally via css.
- node classList property doesn't exist on svg elements in IE/Edge...so have to use getAttribute and setAttribute...annoying I know.

It's a good suggestion to add classes to the elements so they can be styled/animated via css, in fact it would be ideal if all of the animations were handled through css.

So I would suggest just adding two new properties / ctor options - 
lineClassNames: string[] of class names to apply to the line node.
directionSymbolClassNames: string [] of class names to apply to the direction symbol nodes.

Then adding those classes to the node where appropriate. This will allow the line to be animated and also the direction symbols via css if needed. Although IE/Edge don't allow transitions/animations on a lot of svg properties through css.

I'm going to close the PR, happy for you to make those changes and resubmit another or I can make them and send it to you to look at before committing?

Thanks,
Nick

**Comment by cmosnick** [comment]
Hi @nickcam,

Thanks for taking a look at this!  I was going to write something up to help with git, but it looks like you figured it out pretty quickly.  Let me iterate over your comments to make sure I understand them:
- Agreed on this one, no questions here.
- Is there an easy way for a user to add a class to a SimpleLineSymbol graphic node to animate it now?  If that is the case, then your point stands and all of my changes would be unnecessary.  However, if it is not that simple, I think that the user should be able to use this DLS extension to either animate the line, add arrows, or both.  This extension could make it easier to add classes onto the symbol for CSS animation on their end.
- Agreed, it is pretty useless :)
- This can be changed as well, good catch

> So I would suggest just adding two new properties / ctor options - 
> lineClassNames: string[] of class names to apply to the line node.
> directionSymbolClassNames: string [] of class names to apply to the direction symbol nodes.
> 
> Then adding those classes to the node where appropriate. This will allow the line to be animated and also the direction symbols via css if needed. Although IE/Edge don't allow transitions/animations on a lot of svg properties through css.

Correct me if I am totally wrong: Are you suggesting changing the logic behind the direction symbols to be animated solely via CSS as well?  A solution may be to add a class to the symbol and simply dictate the image via CSS if possible?  I'm not completely sure I am understanding your plan going forward in terms of the `directionSymbolClassNames[]` option, but the `lineClassNames` option makes sense to me.  The extension would simply apply the classes to the line and let the user dictate what to do with the classes' animations.

Let me know what you think, I would love to make a good plan going forward.

Best,
Christina

**Comment by nickcam** [comment]
Hi Christine,

The best explanation is an example :). Just knocked up this basic plunkr with the changes planned.
https://plnkr.co/edit/paGK5tDSlvNx1YxdO5ahc?p=preview

As you can see in there it is very simple to add a class to a graphic that uses a SimpleLineSymbol - just need to add `graphic.attr("class", "some-class-name")` to the graphic after it's been added to the map.

Also didn't plan on completely removing the animations from javascript, but instead the `directionSymbolClassNames` property just gives that extra flexibility so callers can potentially use their own animations on directionSymbol nodes via css...in the plunkr it's the basic opacity animation on the polygon.

The only tricky bit was within DirectionalLineSymbol - needed to add any `lineClassNames` defined to the line node in the `graphic-draw` event of the containing layers. This is because at the point the symbol is initialized - `getStroke()` - the graphic hasn't been added to the DOM yet so if the graphic was in the visible extent when first loaded the class wouldn't be applied. Also means can just use `graphic.attr("class", "some-class-name")` to add the class which will work in IE/Edge as I'm pretty sure it just calls setAttribute on the graphics node under the covers.

Thanks,
Nick

**Comment by cmosnick** [comment]
It looks like the plunkr link you posted is broken.

**Comment by nickcam** [comment]
Oh yeah - don't know what happened to it. Here it is again:
https://plnkr.co/edit/oXjG83OKiEeoAlm1hXbi?p=info

**Comment by nickcam** [comment]
Hi @cmosnick,

Sorry took a while to get around to looking at these. I don't think the changes will quite suit as they are. 
I'm going to close the PR and will look at incorporating the updates I had in the plunkr when I get a chance to test them properly.

Thanks,
Nick

**Pull request closed without merging**
